/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BlogPost {
    id: bigint;
    title: string;
    content: string;
    tags: Array<string>;
    publicationDate: Time;
}
export type Time = bigint;
export interface Memory {
    id: bigint;
    title: string;
    description: string;
    imageUrl: string;
}
export interface Education {
    institution: string;
    graduationYear: string;
    degree: string;
}
export interface WorkExperience {
    endDate: string;
    description: string;
    company: string;
    position: string;
    startDate: string;
}
export interface StudyMaterial {
    id: bigint;
    title: string;
    content: string;
    subject: string;
    description: string;
}
export interface Resume {
    education: Array<Education>;
    workExperience: Array<WorkExperience>;
    summary: string;
    skills: Array<string>;
}
export interface Article {
    id: bigint;
    coverImageUrl?: string;
    title: string;
    content: string;
    publicationDate: Time;
}
export interface backendInterface {
    addMemory(title: string, description: string, imageUrl: string): Promise<Memory>;
    addStudyMaterial(title: string, subject: string, description: string, content: string): Promise<StudyMaterial>;
    createArticle(title: string, content: string, coverImageUrl: string | null): Promise<Article>;
    createBlogPost(title: string, content: string, tags: Array<string>): Promise<BlogPost>;
    getAllArticles(): Promise<Array<Article>>;
    getAllBlogPosts(): Promise<Array<BlogPost>>;
    getAllMemories(): Promise<Array<Memory>>;
    getAllStudyMaterials(): Promise<Array<StudyMaterial>>;
    getArticle(id: bigint): Promise<Article>;
    getBlogPost(id: bigint): Promise<BlogPost>;
    getResume(): Promise<Resume | null>;
    getStudyMaterialsBySubject(subject: string): Promise<Array<StudyMaterial>>;
    updateResume(newResume: Resume): Promise<void>;
}
import type { Article as _Article, Resume as _Resume, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMemory(arg0: string, arg1: string, arg2: string): Promise<Memory> {
        if (this.processError) {
            try {
                const result = await this.actor.addMemory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMemory(arg0, arg1, arg2);
            return result;
        }
    }
    async addStudyMaterial(arg0: string, arg1: string, arg2: string, arg3: string): Promise<StudyMaterial> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudyMaterial(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudyMaterial(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createArticle(arg0: string, arg1: string, arg2: string | null): Promise<Article> {
        if (this.processError) {
            try {
                const result = await this.actor.createArticle(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Article_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArticle(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Article_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBlogPost(arg0: string, arg1: string, arg2: Array<string>): Promise<BlogPost> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArticles();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArticles();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPosts();
            return result;
        }
    }
    async getAllMemories(): Promise<Array<Memory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMemories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMemories();
            return result;
        }
    }
    async getAllStudyMaterials(): Promise<Array<StudyMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudyMaterials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudyMaterials();
            return result;
        }
    }
    async getArticle(arg0: bigint): Promise<Article> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticle(arg0);
                return from_candid_Article_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticle(arg0);
            return from_candid_Article_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPost(arg0: bigint): Promise<BlogPost> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return result;
        }
    }
    async getResume(): Promise<Resume | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResume();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResume();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudyMaterialsBySubject(arg0: string): Promise<Array<StudyMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyMaterialsBySubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyMaterialsBySubject(arg0);
            return result;
        }
    }
    async updateResume(arg0: Resume): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResume(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResume(arg0);
            return result;
        }
    }
}
function from_candid_Article_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Article): Article {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Resume]): Resume | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    coverImageUrl: [] | [string];
    title: string;
    content: string;
    publicationDate: _Time;
}): {
    id: bigint;
    coverImageUrl?: string;
    title: string;
    content: string;
    publicationDate: Time;
} {
    return {
        id: value.id,
        coverImageUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.coverImageUrl)),
        title: value.title,
        content: value.content,
        publicationDate: value.publicationDate
    };
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Article>): Array<Article> {
    return value.map((x)=>from_candid_Article_n2(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
