/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Memory = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const StudyMaterial = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subject' : IDL.Text,
  'description' : IDL.Text,
});
export const Time = IDL.Int;
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'coverImageUrl' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publicationDate' : Time,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'publicationDate' : Time,
});
export const Education = IDL.Record({
  'institution' : IDL.Text,
  'graduationYear' : IDL.Text,
  'degree' : IDL.Text,
});
export const WorkExperience = IDL.Record({
  'endDate' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'position' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Resume = IDL.Record({
  'education' : IDL.Vec(Education),
  'workExperience' : IDL.Vec(WorkExperience),
  'summary' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addMemory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Memory], []),
  'addStudyMaterial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [StudyMaterial],
      [],
    ),
  'createArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Article],
      [],
    ),
  'createBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [BlogPost],
      [],
    ),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllMemories' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
  'getAllStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
  'getArticle' : IDL.Func([IDL.Nat], [Article], ['query']),
  'getBlogPost' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
  'getResume' : IDL.Func([], [IDL.Opt(Resume)], ['query']),
  'getStudyMaterialsBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudyMaterial)],
      ['query'],
    ),
  'updateResume' : IDL.Func([Resume], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Memory = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const StudyMaterial = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subject' : IDL.Text,
    'description' : IDL.Text,
  });
  const Time = IDL.Int;
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'coverImageUrl' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publicationDate' : Time,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'publicationDate' : Time,
  });
  const Education = IDL.Record({
    'institution' : IDL.Text,
    'graduationYear' : IDL.Text,
    'degree' : IDL.Text,
  });
  const WorkExperience = IDL.Record({
    'endDate' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'position' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Resume = IDL.Record({
    'education' : IDL.Vec(Education),
    'workExperience' : IDL.Vec(WorkExperience),
    'summary' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addMemory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Memory], []),
    'addStudyMaterial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [StudyMaterial],
        [],
      ),
    'createArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Article],
        [],
      ),
    'createBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [BlogPost],
        [],
      ),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllMemories' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
    'getAllStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
    'getArticle' : IDL.Func([IDL.Nat], [Article], ['query']),
    'getBlogPost' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
    'getResume' : IDL.Func([], [IDL.Opt(Resume)], ['query']),
    'getStudyMaterialsBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudyMaterial)],
        ['query'],
      ),
    'updateResume' : IDL.Func([Resume], [], []),
  });
};

export const init = ({ IDL }) => { return []; };