/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'coverImageUrl' : [] | [string],
  'title' : string,
  'content' : string,
  'publicationDate' : Time,
}
export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'tags' : Array<string>,
  'publicationDate' : Time,
}
export interface Education {
  'institution' : string,
  'graduationYear' : string,
  'degree' : string,
}
export interface Memory {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'imageUrl' : string,
}
export interface Resume {
  'education' : Array<Education>,
  'workExperience' : Array<WorkExperience>,
  'summary' : string,
  'skills' : Array<string>,
}
export interface StudyMaterial {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'subject' : string,
  'description' : string,
}
export type Time = bigint;
export interface WorkExperience {
  'endDate' : string,
  'description' : string,
  'company' : string,
  'position' : string,
  'startDate' : string,
}
export interface _SERVICE {
  'addMemory' : ActorMethod<[string, string, string], Memory>,
  'addStudyMaterial' : ActorMethod<
    [string, string, string, string],
    StudyMaterial
  >,
  'createArticle' : ActorMethod<[string, string, [] | [string]], Article>,
  'createBlogPost' : ActorMethod<[string, string, Array<string>], BlogPost>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllMemories' : ActorMethod<[], Array<Memory>>,
  'getAllStudyMaterials' : ActorMethod<[], Array<StudyMaterial>>,
  'getArticle' : ActorMethod<[bigint], Article>,
  'getBlogPost' : ActorMethod<[bigint], BlogPost>,
  'getResume' : ActorMethod<[], [] | [Resume]>,
  'getStudyMaterialsBySubject' : ActorMethod<[string], Array<StudyMaterial>>,
  'updateResume' : ActorMethod<[Resume], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];